export const CREATE_PHOTO_POST = 'CREATE_PHOTO_POST'
export const INIT_PHOTO_POST = 'INIT_PHOTO_POST'

export const FAVORITES = 'FAVORITES'

export const LOADING_TRUE = 'LOADING_TRUE'
export const LOADING_FALSE = 'LOADING_FALSE'
export const GLOBAL_LOADING_FALSE = 'GLOBAL_LOADING_FALSE'
export const GLOBAL_LOADING_TRUE = 'GLOBAL_LOADING_TRUE'

export const SET_USER = 'SET_USER'
export const DEL_USER = 'DEL_USER'

export const TOAST_VIEW = 'TOAST_VIEW'
export const TOAST_HIDE = 'TOAST_HIDE'

export const HIDDEN_ANIM = 'HIDDEN_ANIM'
export const HIDDEN_PHOTO = 'HIDDEN_PHOTO'

export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_OWN_PHOTOS = 'GET_OWN_PHOTOS'
export const GET_SEARCHED = 'GET_SEARCHED'

